#ifndef _ABSTRACT_GAME_ACTIONS_INDEX_HPP
#define _ABSTRACT_GAME_ACTIONS_INDEX_HPP

enum Abstract_game_actions_index {
        MOVE_LEFT = 5, MOVE_RIGHT, MOVE_DOWN, MOVE_UP, CLIMB_UP, CLIMB_DOWN,
        JUMP, ATTACK_01
};
#endif // !_ABSTRACT_GAME_ACTIONS_INDEX_HPP
